### ISSUE TITLE
Create a frontal org

### ISSUE THREAD

**Issue by fabiantheblind** [frntl/frontal#17]
Should we create a frontal org? It's easier to find and manage?

**Comment by fabiantheblind** [comment]
Should we do this or should we stay here in your account?

**Comment by fabiantheblind** [comment]
@sebastian-meier

**Comment by fabiantheblind** [comment]
I just created the org under the name frntl (frontal is already taken) I would love to pass the repo over to that org so we both have the same possibilities for editing repos. Also all the stuff related to the app can be collected there https://github.com/frntl we can have a gitter chat and so on

**Comment by sebastian-meier** [comment]
Error: You don’t have admin rights to frntl

**Comment by fabiantheblind** [comment]
You are now owner as well
