### ISSUE TITLE
Node and electron version

### ISSUE THREAD

**Issue by fabiantheblind** [frntl/frontal#24]
> Upgrade to Electron 0.34.0
> Atom 1.2.0 stable is on the latest minor version of Electron which uses Chrome 45 and node 4.1.1.  
> http://blog.atom.io/

Should we go for 4.1.1 as well? Or stay with 4.2.2 as set in .nvmrc

**Comment by sebastian-meier** [comment]
Sounds good.

**Comment by fabiantheblind** [comment]
what? stying with 4.2.2?

**Comment by fabiantheblind** [comment]
Let's stay at 4.2.2 for now. Works fine for me
