### ISSUE TITLE
structure of sub-modules

### ISSUE THREAD

**Issue by sebastian-meier** [frntl/frontal#32]
After looking at your parser submodule, if i read it right, you are exporting three individual functions, right?

shouldn't it be like

parser
parser.json
parser.md2json
...

maybe i am reading the code wrong...

**Comment by fabiantheblind** [comment]
Its 4 
Parser as

**Comment by fabiantheblind** [comment]
Take a look into parser.js in src

**Comment by fabiantheblind** [comment]
Of for today

**Comment by sebastian-meier** [comment]
:)

Fabian Morón Zirfas <notifications@github.com> schrieb am Fr., 13. Nov.
2015, 17:52:

**Comment by sebastian-meier** [comment]
ah, ok... nah... but its working... i have to get used to this way of writing code...
but for testing i added parser.json(data)... and it works. YAY!

**Comment by fabiantheblind** [comment]
What Kind ? With modules?

**Comment by sebastian-meier** [comment]
Those exports... Never done that...

Fabian Morón Zirfas <notifications@github.com> schrieb am Fr., 13. Nov.
2015, 19:39:

**Comment by fabiantheblind** [comment]
I like it a lot. It makes small modules that do one thing well.

**Comment by fabiantheblind** [comment]
about my module:  
It exports 3 Things:

```js
parser.json(data)
parser.md2json(data)
parser.md2html(data) 
```
to use it in a es6 way (if you are in /src/main.js)

```js
import * as parser from './controller/parser';
// or like this (not verified)
import {md2json} from './controller/parser';
```

see [https://babeljs.io/docs/learn-es2015/#modules](https://babeljs.io/docs/learn-es2015/#modules)

**Comment by fabiantheblind** [comment]
confirmed

```js
import {md2json} from './controller/parser';
```

That works.
