### ISSUE TITLE
Globals

### ISSUE THREAD

**Issue by sebastian-meier** [frntl/frontal#36]
I am almost done cleaning the main.js and sorting stuff into sub-modules. For the interaction with the individual pages we need to keep references to some functions/variables in the global-scope. Where should we create those globals? Should they be created in the main.js or in the sub-modules (actually not sure if sub-modules can register globals??).

**Comment by fabiantheblind** [comment]
I think a module called globals would be good. So we can

```js
import {dog, cat} from ',/globals';
```

This would allows to load only some of the globals or all of them

```js
import * as globals from './globals';
```

**Comment by sebastian-meier** [comment]
Sounds good. I am still a bit struggling with references to certain module
bits across sub modules and stuff...
Fabian Morón Zirfas <notifications@github.com> schrieb am Sa., 14. Nov.
2015 um 10:02:

**Comment by fabiantheblind** [comment]
https://nodejs.org/docs/v4.2.2/api/globals.html#globals_global

http://www.hacksparrow.com/global-variables-in-node-js.html

http://stackoverflow.com/questions/5447771/node-js-global-variables

**Comment by sebastian-meier** [comment]
Thx.
Fabian Morón Zirfas <notifications@github.com> schrieb am Sa., 14. Nov.
2015 um 10:08:

**Comment by fabiantheblind** [comment]
I think the best is always think of the path not to import more than you need.

**Comment by fabiantheblind** [comment]
hm. I think naming it globals is not wise. Should be something like settings or config or hallapaluzasuperthingy. Best would be to avoid globals and pass them around as modules. So don't do what the second article says. :-)

**Comment by sebastian-meier** [comment]
right now i got rid of all the globals that are used inside the normal
modules.
maybe we can create a module called "interface" that allows the
site-specific js to communicate to the modules.
the interface can than only include very specific functions to the
global-scope as an additional security measurement (as suggested by you in
the beginning).



Fabian Morón Zirfas <notifications@github.com> schrieb am Sa., 14. Nov.
2015 um 10:12 Uhr:

**Comment by fabiantheblind** [comment]
good idea. interface it is. Having no globals is also a good thing. If you read the stackoverflow I'll come to the conclusion that there should not be any globals
