### ISSUE TITLE
Themes location?

### ISSUE THREAD

**Issue by fabiantheblind** [frntl/frontal#7]
see also https://github.com/sebastian-meier/frontal-themes/issues/1

**Comment by sebastian-meier** [comment]
I though it would be nice if the user could define a folder where the themes are stored. My idea was similar to the wordpress way of storing themes. A folder with all themes, each folder contains (ideally) a preview.png, package.json (with name and description) as well as all the other files... 

In FRONTAL itself we could build a theme-page where the user can select which theme she wants to use...

**Comment by fabiantheblind** [comment]
I would suggest a managed version without the user telling frontal where the themes are the ~/.frontal folder see https://github.com/sebastian-meier/frontal-themes/issues/1
