### ISSUE TITLE
Markdown to JSON

### ISSUE THREAD

**Issue by sebastian-meier** [frntl/frontal#9]
One thing we need is a Markdown Parser that ideally spits out a JSON-array filled with objects for each slide.

**Comment by fabiantheblind** [comment]
Do we really need to split it into an json? 
Why don't we split just at the hr

   \---

and parse the rest into a 100% width/height div

**Comment by sebastian-meier** [comment]
i think doing a full conversion gives people more flexibility, for example if someone wants to display a row of images and builds her own theme-template for this, she can easily do this.

but we could build the markdown parser in a way, that the md file is split at hr and then the whole content of each slide is just stored as one parameter in the json 

var slides [
{content:'content of slide 1'},
{content:'content of slide 2'}
];

Which is then inserted and rendered in a theme-template.

Before inserting the data into the json i would already run a markdown-renderer on the slide-content.

**Comment by fabiantheblind** [comment]
Hi talked to @schlompf about that and we came to the thought that it is a double action parsing the md to json to insert it into html. I would suggest we start by just parsing per slide like you described above. If we get the feeling that we need more control we can split the source me further. A line of images could be done just by the template. e.g. A list of images gets parsed into images next to each other. This can be done by css + js from the template and does not need to be in the core.

**Comment by fabiantheblind** [comment]
needs parsing at  

    \---

also needs detection of comments in that slide

**Comment by fabiantheblind** [comment]
The markdown-js Package already does that. See my lates pr

**Comment by fabiantheblind** [comment]
“evilstreak/markdown-js”

https://github.com/evilstreak/markdown-js
